"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 5000

[gcloud]
disabled = true

[kubernetes]
disabled = false
detect_extensions = ['yaml', 'yml']
contexts = [
  {context_pattern = "(.*prod.*)", symbol = "⚠️ ⚠️ ⚠️ "}
]

[docker_context]
disabled = true

