[scrolling]
history = 0

[font]
size = 14
normal = { family = "Jetbrains Mono", style = "Regular"}

[terminal.shell] 
program = "/opt/homebrew/bin/zellij"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

[window]
startup_mode = "Fullscreen"

[terminal]
