[scrolling]
history = 0

[font]
size = 13
normal = { family = "Jetbrains Mono", style = "Regular"}

[shell] 
program = "/opt/homebrew/bin/zellij"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
