theme = "darcula"

[editor]
bufferline = "multiple"
end-of-line-diagnostics = "hint"
cursorline = true

[editor.inline-diagnostics]
cursor-line = "error"

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "none"

[editor.statusline]
left = ["version-control", "mode", "spinner"]

[editor.lsp]
display-inlay-hints = true
