[[snippets]]
  description = "Generate cert and key"
  command = "openssl req <output-format=-x509> -newkey rsa:2048 -keyout key.pem -out cert.pem -sha256 -days 3650 -nodes -subj \"/<subj>/\""
  output = ""
